-- PostgreSQL consolidated baseline, including migrations 001-018.
-- New/empty database: run this file only. Do NOT run 001-018 afterwards.
-- DEFAULT RESET: truncates users, bank accounts, billing accounts/transactions/
-- installments, debts, debt payments, savings, saving movements and split bill groups.
-- Three-month settled-history visibility is a service rule, not a schema column.
-- Existing wallet_providers rows (including custom platforms) are retained.
-- Change finance_tracker.reset to 'off' for non-destructive initialization only.
-- Existing historical billing schemas require their pending migrations first.
-- Tables/constraints are retained; the database/schema is not dropped.
-- UUIDs are generated by the application; no extensions are required.
BEGIN;

SELECT set_config('finance_tracker.reset', 'on', true);
DO $$ BEGIN
    IF to_regclass('billing_platforms') IS NOT NULL THEN
        RAISE EXCEPTION 'Jalankan migration 008 sebelum memakai baseline terbaru.';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    google_sub VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL,
    name VARCHAR(255) NOT NULL,
    picture_url VARCHAR(2048),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_users_google_sub UNIQUE (google_sub)
);


CREATE TABLE IF NOT EXISTS wallet_providers (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    bank_f INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_wallet_provider_bank_f CHECK (bank_f IN (0, 1))
);

CREATE TABLE IF NOT EXISTS billing_accounts (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    platform_id INTEGER NOT NULL REFERENCES wallet_providers(id),
    platform_type VARCHAR(20) NOT NULL,
    account_type VARCHAR(100),
    account_number_encrypted TEXT,
    valid_thru VARCHAR(7),
    has_fixed_bill_date BOOLEAN NOT NULL,
    billing_date INTEGER,
    due_date INTEGER,
    monthly_fee NUMERIC(18,0) NOT NULL DEFAULT 0,
    payment_fee NUMERIC(18,0) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_billing_account_fees CHECK (monthly_fee BETWEEN 0 AND 1000000000000 AND payment_fee BETWEEN 0 AND 1000000000000),
    CONSTRAINT ck_billing_account_type CHECK (platform_type IN ('CREDIT_CARD', 'PAY_LATER')),
    CONSTRAINT ck_billing_card_fields CHECK (
        (platform_type = 'CREDIT_CARD' AND account_type IS NOT NULL AND account_number_encrypted IS NOT NULL AND valid_thru IS NOT NULL)
        OR (platform_type = 'PAY_LATER' AND account_type IS NULL AND account_number_encrypted IS NULL AND valid_thru IS NULL)
    ),
    CONSTRAINT ck_billing_fixed_dates CHECK (
        (has_fixed_bill_date = TRUE AND billing_date IS NOT NULL AND due_date IS NOT NULL AND billing_date BETWEEN 1 AND 31 AND due_date BETWEEN 1 AND 31)
        OR (has_fixed_bill_date = FALSE AND billing_date IS NULL AND due_date IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_billing_accounts_user_id ON billing_accounts(user_id);

CREATE TABLE IF NOT EXISTS billing_transactions (
    id UUID PRIMARY KEY,
    account_id UUID NOT NULL REFERENCES billing_accounts(id),
    description VARCHAR(255) NOT NULL,
    tenor INTEGER NOT NULL CHECK (tenor IN (0, 3, 6, 9, 12, 18, 24)),
    transaction_date DATE,
    first_installment DATE NOT NULL,
    last_installment DATE,
    transaction_kind VARCHAR(20) NOT NULL DEFAULT 'ONE_TIME',
    stopped_on DATE,
    recurring_billing_day INTEGER,
    recurring_due_day INTEGER,
    amount NUMERIC(18, 0) NOT NULL CHECK (amount > 0),
    notes VARCHAR(2000) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_billing_transaction_kind CHECK (
        (transaction_kind = 'ONE_TIME' AND tenor = 0 AND last_installment IS NOT NULL AND stopped_on IS NULL)
        OR (transaction_kind = 'INSTALLMENT' AND tenor > 0 AND last_installment IS NOT NULL AND stopped_on IS NULL)
        OR (transaction_kind = 'SUBSCRIPTION' AND tenor = 0 AND last_installment IS NULL)
    )
);
CREATE INDEX IF NOT EXISTS ix_billing_transactions_account ON billing_transactions(account_id);

CREATE TABLE IF NOT EXISTS billing_installments (
    id UUID PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES billing_transactions(id),
    sequence INTEGER NOT NULL,
    amount NUMERIC(18, 0) NOT NULL CHECK (amount > 0),
    due_date DATE NOT NULL,
    charged_on DATE,
    paid_at TIMESTAMPTZ,
    CONSTRAINT ck_billing_installment_sequence CHECK (sequence >= 1),
    UNIQUE (transaction_id, sequence)
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    platform_id INTEGER NOT NULL REFERENCES wallet_providers(id),
    account_number_encrypted TEXT NOT NULL,
    card_number_encrypted TEXT NOT NULL,
    valid_thru VARCHAR(7) NOT NULL,
    admin_fee NUMERIC(18, 0) NOT NULL DEFAULT 0,
    others_fee NUMERIC(18, 0) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_bank_account_fees CHECK (admin_fee BETWEEN 0 AND 1000000000000 AND others_fee BETWEEN 0 AND 1000000000000)
);
CREATE INDEX IF NOT EXISTS ix_bank_accounts_user_id ON bank_accounts(user_id);

CREATE TABLE IF NOT EXISTS debts (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    kind VARCHAR(20) NOT NULL,
    person_name VARCHAR(255) NOT NULL,
    principal NUMERIC(18, 0) NOT NULL,
    transaction_date DATE NOT NULL,
    due_date DATE,
    source_bank_account_id UUID REFERENCES bank_accounts(id) ON DELETE SET NULL,
    source_bank_name VARCHAR(100),
    source_account_number_masked VARCHAR(30),
    installment_count INTEGER NOT NULL DEFAULT 0,
    installment_amounts JSON NOT NULL DEFAULT '[]',
    interest_type VARCHAR(20) NOT NULL,
    interest_rate NUMERIC(5, 2) NOT NULL,
    notes VARCHAR(2000) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_debt_installments CHECK (installment_count BETWEEN 0 AND 60 AND (installment_count = 0 OR due_date IS NOT NULL)),
    CONSTRAINT ck_debt_kind CHECK (kind IN ('DEBT', 'RECEIVABLE')),
    CONSTRAINT ck_debt_principal CHECK (principal > 0 AND principal <= 1000000000000),
    CONSTRAINT ck_debt_interest CHECK (
        (interest_type = 'NONE' AND interest_rate = 0)
        OR (interest_type = 'MONTHLY' AND interest_rate > 0 AND interest_rate <= 100)
    ),
    CONSTRAINT ck_debt_due_date CHECK (due_date IS NULL OR due_date >= transaction_date)
);
CREATE INDEX IF NOT EXISTS ix_debts_user_id ON debts(user_id);

CREATE TABLE IF NOT EXISTS debt_payments (
    id UUID PRIMARY KEY,
    debt_id UUID NOT NULL REFERENCES debts(id),
    request_id UUID NOT NULL,
    sequence INTEGER NOT NULL,
    amount NUMERIC(18, 0) NOT NULL,
    payment_date DATE NOT NULL,
    notes VARCHAR(2000) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (debt_id, request_id),
    UNIQUE (debt_id, sequence),
    CONSTRAINT ck_debt_payment_amount CHECK (amount > 0 AND amount <= 9007199254740991),
    CONSTRAINT ck_debt_payment_sequence CHECK (sequence >= 1)
);

CREATE TABLE IF NOT EXISTS savings (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    kind VARCHAR(20) NOT NULL,
    metal_type VARCHAR(10),
    name VARCHAR(255) NOT NULL,
    opening_amount NUMERIC(18,3) NOT NULL,
    start_date DATE NOT NULL,
    bank_account_id UUID REFERENCES bank_accounts(id) ON DELETE SET NULL,
    bank_name VARCHAR(100),
    bank_account_masked VARCHAR(30),
    weight_per_piece NUMERIC(12,3),
    pieces INTEGER,
    purchase_cost NUMERIC(18,0),
    price_per_gram NUMERIC(18,0),
    price_date DATE,
    maturity_date DATE,
    interest_rate NUMERIC(5,2),
    notes VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_saving_kind CHECK (kind IN ('CASH','GOLD','DEPOSIT')),
    CONSTRAINT ck_saving_opening CHECK (opening_amount > 0),
    CONSTRAINT ck_saving_metal_type CHECK (
        (kind = 'GOLD' AND metal_type IS NOT NULL AND metal_type IN ('GOLD','SILVER'))
        OR (kind <> 'GOLD' AND metal_type IS NULL)
    )
);
CREATE INDEX IF NOT EXISTS ix_savings_user_id ON savings(user_id);
CREATE TABLE IF NOT EXISTS saving_movements (
    id UUID PRIMARY KEY,
    saving_id UUID NOT NULL REFERENCES savings(id),
    request_id UUID NOT NULL,
    sequence INTEGER NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(18,3) NOT NULL,
    movement_date DATE NOT NULL,
    notes VARCHAR(2000) NOT NULL,
    UNIQUE (saving_id, request_id),
    UNIQUE (saving_id, sequence),
    CONSTRAINT ck_saving_movement CHECK (direction IN ('ADD','REMOVE') AND amount > 0)
);

-- IF NOT EXISTS is not an upgrade mechanism. Fail clearly for older schemas.
CREATE TABLE IF NOT EXISTS split_bill_groups (
	id UUID NOT NULL,
	user_id UUID NOT NULL,
	name VARCHAR(200) NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	version INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT ck_split_bill_version CHECK (version > 0),
	CONSTRAINT ck_split_group_name CHECK (length(trim(name)) > 0),
	CONSTRAINT ck_split_group_dates CHECK (start_date >= '2000-01-01' AND end_date >= start_date),
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS split_bill_participants (
	group_id UUID NOT NULL,
	id UUID NOT NULL,
	name VARCHAR(80) NOT NULL,
	position INTEGER NOT NULL,
	PRIMARY KEY (group_id, id),
	CONSTRAINT uq_split_participant_position UNIQUE (group_id, position),
	CONSTRAINT ck_split_participant_position CHECK (position BETWEEN 0 AND 19),
	CONSTRAINT ck_split_participant_name CHECK (length(trim(name)) > 0),
	FOREIGN KEY(group_id) REFERENCES split_bill_groups (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS split_bill_expenses (
	group_id UUID NOT NULL,
	id UUID NOT NULL,
	name VARCHAR(200) NOT NULL,
	expense_date DATE NOT NULL,
	paid_by UUID NOT NULL,
	service_mode VARCHAR(10) NOT NULL,
	service_value NUMERIC(15, 2) NOT NULL,
	tax_mode VARCHAR(10) NOT NULL,
	tax_value NUMERIC(15, 2) NOT NULL,
	tax_includes_service BOOLEAN NOT NULL,
	fee_allocation VARCHAR(12) NOT NULL,
	receipt_total BIGINT,
	notes VARCHAR(2000) NOT NULL,
	position INTEGER NOT NULL,
	PRIMARY KEY (group_id, id),
	FOREIGN KEY(group_id, paid_by) REFERENCES split_bill_participants (group_id, id),
	CONSTRAINT uq_split_expense_position UNIQUE (group_id, position),
	CONSTRAINT ck_split_expense_position CHECK (position BETWEEN 0 AND 99),
	CONSTRAINT ck_split_expense_name CHECK (length(trim(name)) > 0),
	CONSTRAINT ck_split_service CHECK (service_mode IN ('AMOUNT','PERCENT') AND service_value >= 0 AND service_value <= 1000000000000 AND (service_mode <> 'PERCENT' OR service_value <= 100) AND (service_mode <> 'AMOUNT' OR service_value = round(service_value))),
	CONSTRAINT ck_split_tax CHECK (tax_mode IN ('AMOUNT','PERCENT') AND tax_value >= 0 AND tax_value <= 1000000000000 AND (tax_mode <> 'PERCENT' OR tax_value <= 100) AND (tax_mode <> 'AMOUNT' OR tax_value = round(tax_value))),
	CONSTRAINT ck_split_fee_allocation CHECK (fee_allocation IN ('PROPORTIONAL','EQUAL','MIXED')),
	CONSTRAINT ck_split_receipt_total CHECK (receipt_total IS NULL OR receipt_total BETWEEN 0 AND 1000000000000),
	FOREIGN KEY(group_id) REFERENCES split_bill_groups (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS split_bill_items (
	group_id UUID NOT NULL,
	expense_id UUID NOT NULL,
	id UUID NOT NULL,
	name VARCHAR(200) NOT NULL,
	amount BIGINT NOT NULL,
	split_mode VARCHAR(6) NOT NULL,
	position INTEGER NOT NULL,
	PRIMARY KEY (group_id, expense_id, id),
	FOREIGN KEY(group_id, expense_id) REFERENCES split_bill_expenses (group_id, id) ON DELETE CASCADE,
	CONSTRAINT uq_split_item_position UNIQUE (group_id, expense_id, position),
	CONSTRAINT ck_split_item_position CHECK (position BETWEEN 0 AND 99),
	CONSTRAINT ck_split_item_name CHECK (length(trim(name)) > 0),
	CONSTRAINT ck_split_item_amount CHECK (amount > 0 AND amount <= 1000000000000),
	CONSTRAINT ck_split_item_mode CHECK (split_mode IN ('EQUAL','CUSTOM'))
);

CREATE TABLE IF NOT EXISTS split_bill_shares (
	group_id UUID NOT NULL,
	expense_id UUID NOT NULL,
	item_id UUID NOT NULL,
	participant_id UUID NOT NULL,
	amount BIGINT NOT NULL,
	position INTEGER NOT NULL,
	PRIMARY KEY (group_id, expense_id, item_id, participant_id),
	FOREIGN KEY(group_id, expense_id, item_id) REFERENCES split_bill_items (group_id, expense_id, id) ON DELETE CASCADE,
	FOREIGN KEY(group_id, participant_id) REFERENCES split_bill_participants (group_id, id),
	CONSTRAINT uq_split_share_position UNIQUE (group_id, expense_id, item_id, position),
	CONSTRAINT ck_split_share_position CHECK (position BETWEEN 0 AND 19),
	CONSTRAINT ck_split_share_amount CHECK (amount BETWEEN 0 AND 1000000000000)
);
CREATE INDEX IF NOT EXISTS ix_split_bill_groups_user_id ON split_bill_groups(user_id);

CREATE TABLE IF NOT EXISTS routine_plans (
	id UUID NOT NULL,
	user_id UUID NOT NULL,
	kind VARCHAR(20) NOT NULL,
	recipient VARCHAR(120) NOT NULL,
	name VARCHAR(200) NOT NULL,
	amount BIGINT NOT NULL,
	status VARCHAR(12) NOT NULL,
	first_due_date DATE NOT NULL,
	interval_months INTEGER NOT NULL,
	total_cycles INTEGER NOT NULL,
	initial_paid INTEGER NOT NULL,
	destination_bank_id UUID,
	billing_transaction_id UUID,
	debt_id UUID,
	saving_id UUID,
	notes VARCHAR(2000) NOT NULL,
	version INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT ck_routine_kind CHECK (kind IN ('SUBSCRIPTION','CONTRIBUTION','TRANSFER')),
	CONSTRAINT ck_routine_status CHECK (status IN ('ACTIVE','NOTE','STOPPED')),
	CONSTRAINT ck_routine_amount CHECK (amount BETWEEN 0 AND 1000000000000 AND (status <> 'ACTIVE' OR amount > 0)),
	CONSTRAINT ck_routine_interval CHECK (interval_months BETWEEN 1 AND 12),
	CONSTRAINT ck_routine_cycles CHECK (total_cycles BETWEEN 0 AND 60 AND initial_paid >= 0 AND (total_cycles = 0 OR initial_paid <= total_cycles)),
	CONSTRAINT ck_routine_version CHECK (version > 0),
	FOREIGN KEY(user_id) REFERENCES users (id),
	FOREIGN KEY(destination_bank_id) REFERENCES bank_accounts (id) ON DELETE SET NULL,
	FOREIGN KEY(billing_transaction_id) REFERENCES billing_transactions (id) ON DELETE SET NULL,
	FOREIGN KEY(debt_id) REFERENCES debts (id) ON DELETE SET NULL,
	FOREIGN KEY(saving_id) REFERENCES savings (id)
);

CREATE INDEX IF NOT EXISTS ix_routine_owner ON routine_plans (user_id);

CREATE TABLE IF NOT EXISTS routine_payments (
	id UUID NOT NULL,
	plan_id UUID NOT NULL,
	request_id UUID NOT NULL,
	sequence INTEGER NOT NULL,
	due_date DATE NOT NULL,
	voided_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_routine_payment_request UNIQUE (plan_id, request_id),
	CONSTRAINT ck_routine_payment_sequence CHECK (sequence > 0),
	FOREIGN KEY(plan_id) REFERENCES routine_plans (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_routine_payment_sequence ON routine_payments (plan_id, sequence) WHERE voided_at IS NULL;

CREATE TABLE IF NOT EXISTS ledger_transactions (
	id UUID NOT NULL,
	user_id UUID NOT NULL,
	kind VARCHAR(10) NOT NULL,
	category VARCHAR(20) NOT NULL,
	description VARCHAR(323) NOT NULL,
	amount BIGINT NOT NULL,
	transaction_date DATE NOT NULL,
	source_bank_id UUID,
	destination_bank_id UUID,
	source_label VARCHAR(150) NOT NULL,
	destination_label VARCHAR(150) NOT NULL,
	notes VARCHAR(2000) NOT NULL,
	routine_payment_id UUID,
	billing_installment_id UUID,
	debt_payment_id UUID,
	saving_movement_id UUID,
	request_id UUID,
	request_hash VARCHAR(64),
	legacy_id VARCHAR(200),
	voided_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ledger_legacy UNIQUE (user_id, legacy_id),
	CONSTRAINT uq_ledger_debt_payment UNIQUE (debt_payment_id),
	CONSTRAINT uq_ledger_saving_movement UNIQUE (saving_movement_id),
	CONSTRAINT uq_ledger_request UNIQUE (user_id, request_id),
	CONSTRAINT ck_ledger_kind CHECK (kind IN ('income','expense','transfer')),
	CONSTRAINT ck_ledger_amount CHECK (amount > 0 AND amount <= 1000000000000),
	CONSTRAINT ck_ledger_distinct_banks CHECK (source_bank_id IS NULL OR destination_bank_id IS NULL OR source_bank_id <> destination_bank_id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	FOREIGN KEY(source_bank_id) REFERENCES bank_accounts (id) ON DELETE SET NULL,
	FOREIGN KEY(destination_bank_id) REFERENCES bank_accounts (id) ON DELETE SET NULL,
	UNIQUE (routine_payment_id),
	FOREIGN KEY(routine_payment_id) REFERENCES routine_payments (id),
	FOREIGN KEY(billing_installment_id) REFERENCES billing_installments (id) ON DELETE SET NULL,
	FOREIGN KEY(debt_payment_id) REFERENCES debt_payments (id) ON DELETE SET NULL,
	FOREIGN KEY(saving_movement_id) REFERENCES saving_movements (id)
);

CREATE INDEX IF NOT EXISTS ix_ledger_owner_date ON ledger_transactions (user_id, transaction_date);

CREATE UNIQUE INDEX IF NOT EXISTS uq_ledger_billing_installment ON ledger_transactions (billing_installment_id) WHERE voided_at IS NULL;

CREATE TABLE IF NOT EXISTS transaction_imports (
	user_id UUID NOT NULL,
	imported_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (user_id),
	FOREIGN KEY(user_id) REFERENCES users (id)
);

DO $$
DECLARE required_column RECORD;
BEGIN
    IF to_regclass('billing_platform_types') IS NOT NULL OR EXISTS (
        SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema()
        AND table_name = 'wallet_providers' AND column_name = 'platform_type'
    ) THEN
        RAISE EXCEPTION 'Struktur billing lama: jalankan migration yang belum diterapkan sampai 018.';
    END IF;
    FOR required_column IN SELECT * FROM (VALUES
        ('savings', 'opening_amount'),
        ('savings', 'metal_type'),
        ('savings', 'price_date'),
        ('routine_plans', 'version'),
        ('ledger_transactions', 'request_hash'),
        ('ledger_transactions', 'saving_movement_id'),
        ('routine_plans', 'saving_id'),
        ('ledger_transactions', 'kind'),
        ('split_bill_groups', 'version'),
        ('split_bill_groups', 'name'),
        ('split_bill_shares', 'participant_id'),
        ('billing_accounts', 'monthly_fee'),
        ('billing_accounts', 'payment_fee'),
        ('saving_movements', 'request_id'),
        ('wallet_providers', 'bank_f'),
        ('debts', 'source_bank_account_id'),
        ('debts', 'installment_amounts'),
        ('debts', 'installment_count'),
        ('billing_transactions', 'transaction_date'),
        ('billing_transactions', 'transaction_kind'),
        ('billing_transactions', 'stopped_on'),
        ('billing_transactions', 'recurring_billing_day'),
        ('billing_transactions', 'recurring_due_day'),
        ('billing_installments', 'charged_on')
    ) AS required(table_name, column_name)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns c
            WHERE c.table_schema = current_schema() AND c.table_name = required_column.table_name
            AND c.column_name = required_column.column_name) THEN
            RAISE EXCEPTION 'Kolom %.% belum tersedia: jalankan migration yang belum diterapkan sampai 018.', required_column.table_name, required_column.column_name;
        END IF;
    END LOOP;
END $$;

-- Explicit table list: never cascade into other tables or truncate platforms.
DO $$
BEGIN
    IF current_setting('finance_tracker.reset')::boolean THEN
        TRUNCATE TABLE ledger_transactions, routine_payments, routine_plans, transaction_imports, split_bill_shares, split_bill_items, split_bill_expenses, split_bill_participants, split_bill_groups, saving_movements, savings, bank_accounts, debt_payments, debts, billing_installments, billing_transactions, billing_accounts, users
            RESTART IDENTITY;
    END IF;
END $$;

INSERT INTO wallet_providers (id, name, bank_f) VALUES
    (1, 'BCA', 1),
    (2, 'BRI', 1),
    (3, 'GoPay Later', 0),
    (4, 'ShopeePay Later', 0),
    (5, 'Kredivo', 0),
    (6, 'CareNow', 0),
    (7, 'Blibli Pay Later', 0)
ON CONFLICT DO NOTHING;

COMMIT;
